### PR TITLE
installing libraries into /usr/lib64 instead of /usr/lib for 64-bit architecture

### PR DESCRIPTION
**Pull request by saik-intel**
for 64-bit architecture

Signed-off-by: Saikishore Konda <saikishore.konda@intel.com>

### CODE REVIEW

**Comment by miguelinux** [comment]
When possible, please follow 
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by miguelinux** [comment]
Please consider #10 to improve this PR

**Comment by miguelinux** [comment]
or use #11 instead ;-)

**Comment by saik-intel** [comment]
Agree that #11  is better solution, hence closing this PR.

**Pull request closed without merging**
